sms/sms/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^sms/', include('students.urls', namespace='student')),
]

sms/students/urls.py
from django.conf.urls import url, include

from .views import (under_contruction,
                    StudentListView,
                    StudentDetailView,
                    StudentCreateView,
                    ParentCreateView,
                    )

urlpatterns = [
    url(r'^$', StudentListView.as_view(), name="list"),
    url(r'^(?P<pk>\d+)/$', StudentDetailView.as_view(), name="detail"),
    url(r'^create/$', StudentCreateView.as_view(), name="create"),
    url(r'^createparent/$', ParentCreateView.as_view(), name="createp"),
]

sms/students/models.py
from __future__ import unicode_literals

from django.db import models
from django.urls import reverse

class Parent(models.Model):
    pfirst_name = models.CharField(max_length=50, verbose_name="First Name")
    plast_name = models.CharField(max_length=50, verbose_name="Last Name")
    pemail = models.EmailField(verbose_name="Email Address")
    mobile_ph = models.CharField(max_length=10, verbose_name="Mobile Phone")
    paddress = models.TextField(verbose_name="Address")
    job = models.CharField(max_length=50, verbose_name="Job")
    office_addr = models.TextField(verbose_name="Office Address")

    def __unicode__(self):
        return "%s %s" % (self.pfirst_name, self.plast_name)

    def get_absolute_url(self):
        return reverse("student:list")

class Student(models.Model):
    first_name = models.CharField(max_length=50, verbose_name="First Name")
    middle_name = models.CharField(max_length=50, verbose_name="Middle Name", blank=True, null=True)
    last_name = models.CharField(max_length=50, verbose_name="Last Name")
    email_id = models.EmailField(blank=True, null=True)
    address = models.TextField(verbose_name="Address")
    dob = models.DateField(verbose_name="Date of Birth")
    mobile_ph = models.CharField(max_length=10, verbose_name="Mobile Phone", blank=True, null=True)
    doj = models.DateField(verbose_name="Date of Joining")
    parent = models.ForeignKey(Parent)

    def __unicode__(self):
        return "%s %s" % (self.first_name, self.last_name)

    def get_absolute_url(self):
        return reverse("student:detail", kwargs={'pk': self.pk})

sms/students/forms.py
from django import forms

from .models import Student, Parent

class StudentCreateForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = [
            "first_name",
            "last_name",
            "email_id",
            "address",
            "dob",
            "mobile_ph",
            "doj",
            "parent",
        ]

class ParentCreateForm(forms.ModelForm):
    class Meta:
        model = Parent
        fields = [
            "pfirst_name",
            "plast_name",
            "pemail",
            "mobile_ph",
            "paddress",
            "job",
            "office_addr",
        ]

sms/students/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import (ListView,
                                  DeleteView,
                                  DetailView,
                                  CreateView,
                                  UpdateView,
                                  )

from .models import Student, Parent
from .forms import StudentCreateForm, ParentCreateForm

# Creating Student and Parent
class StudentCreateView(CreateView):
    form_class = StudentCreateForm
    template_name = "students/student_form.html"

class ParentCreateView(CreateView):
    form_class = ParentCreateForm
    template_name = "students/parent_form.html"

# Modify Student / Parent details
class StudentUpdateView(UpdateView):
    pass
# List Student details
class StudentListView(ListView):
    model = Student

# Student Detail
class StudentDetailView(DetailView):
    model = Student

# Delete Student and Parent details

def under_contruction(request):
    return HttpResponse("Under construction")

sms/students/templates/students/parent_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
</body>
</html>

sms/students/templates/students/student_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action=""  method="post">{% csrf_token %}
    <p>Are you sure to delete student {{ object }}</p>
    <input type="submit" value="Delete Confirm">
</form>
</body>
</html>

sms/students/templates/students/student_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<b>Student Name:</b> {{ object.first_name }}  {{ object.last_name }}<br>
<b>Student DOB:</b> {{ object.dob }} <br>
<b>Address:</b>{{ object.address }} <br>
<b>Parent Name:</b> {{ object.parent }} <br>
</body>
</html>

sms/students/templates/students/student_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
<br>
<a href="{% url 'student:createp' %}">Create Parent</a>
</body>
</html>

sms/students/templates/students/student_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if object_list %}
<ul>
{% for student in object_list %}
<li><a href="{{ student.get_absolute_url }}">{{ student.first_name }}</a></li>
{% endfor %}
</ul>
{% else %}
<h1>No Students</h1>
{% endif %}
<a href="{% url 'student:create' %}">Create Student</a>
</body>
</html>